{
  "timestamp": "2025-09-27T20:22:34.692715",
  "pytest_available": true,
  "fastapi_available": true,
  "tests": {},
  "pytest_exit_code": 1,
  "pytest_stdout": "============================= test session starts =============================\ncollecting ... collected 27 items\n\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_middleware_initialization PASSED [  3%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_bypass_paths PASSED [  7%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_missing_authorization_header PASSED [ 11%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_invalid_authorization_format PASSED [ 14%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_empty_bearer_token PASSED [ 18%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_valid_token_extraction PASSED [ 22%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_token_validation_success PASSED [ 25%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_token_validation_failure PASSED [ 29%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_authentication_error_response_creation PASSED [ 33%]\ntests/test_authentication_integration.py::TestAuthenticationMiddleware::test_internal_error_response_creation PASSED [ 37%]\ntests/test_authentication_integration.py::TestAuthenticationHelper::test_get_user_context_success ERROR [ 40%]\ntests/test_authentication_integration.py::TestAuthenticationHelper::test_get_user_context_none FAILED [ 44%]\ntests/test_authentication_integration.py::TestAuthenticationHelper::test_is_authenticated_true ERROR [ 48%]\ntests/test_authentication_integration.py::TestAuthenticationHelper::test_is_authenticated_false FAILED [ 51%]\ntests/test_authentication_integration.py::TestAuthenticationHelper::test_require_authentication_success ERROR [ 55%]\ntests/test_authentication_integration.py::TestAuthenticationHelper::test_require_authentication_failure FAILED [ 59%]\ntests/test_authentication_integration.py::TestAuthenticationHelper::test_get_user_id ERROR [ 62%]\ntests/test_authentication_integration.py::TestAuthenticationHelper::test_get_username ERROR [ 66%]\ntests/test_authentication_integration.py::TestMCPServerAuthenticationIntegration::test_cognito_authenticator_initialization PASSED [ 70%]\ntests/test_authentication_integration.py::TestMCPServerAuthenticationIntegration::test_token_validator_initialization PASSED [ 74%]\ntests/test_authentication_integration.py::TestMCPServerAuthenticationIntegration::test_invalid_token_validation PASSED [ 77%]\ntests/test_authentication_integration.py::TestMCPServerAuthenticationIntegration::test_malformed_token_validation PASSED [ 81%]\ntests/test_authentication_integration.py::TestMCPServerAuthenticationIntegration::test_middleware_factory_creation PASSED [ 85%]\ntests/test_authentication_integration.py::TestMCPServerAuthenticationIntegration::test_health_endpoint_bypass PASSED [ 88%]\ntests/test_authentication_integration.py::TestAuthenticationErrorScenarios::test_expired_token_error PASSED [ 92%]\ntests/test_authentication_integration.py::TestAuthenticationErrorScenarios::test_invalid_signature_error PASSED [ 96%]\ntests/test_authentication_integration.py::TestAuthenticationErrorScenarios::test_jwks_fetch_error PASSED [100%]\n\n=================================== ERRORS ====================================\n__ ERROR at setup of TestAuthenticationHelper.test_get_user_context_success ___\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 310\n      def test_get_user_context_success(self, mock_request_with_context, valid_user_context):\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 294\n      @pytest.fixture\n      def mock_request_with_context(self, valid_user_context):\nE       fixture 'valid_user_context' not found\n>       available fixtures: _class_scoped_runner, _function_scoped_runner, _module_scoped_runner, _package_scoped_runner, _session_scoped_runner, anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, doctest_namespace, event_loop_policy, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, mock_request_with_context, mock_request_without_context, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py:294\n____ ERROR at setup of TestAuthenticationHelper.test_is_authenticated_true ____\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 320\n      def test_is_authenticated_true(self, mock_request_with_context):\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 294\n      @pytest.fixture\n      def mock_request_with_context(self, valid_user_context):\nE       fixture 'valid_user_context' not found\n>       available fixtures: _class_scoped_runner, _function_scoped_runner, _module_scoped_runner, _package_scoped_runner, _session_scoped_runner, anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, doctest_namespace, event_loop_policy, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, mock_request_with_context, mock_request_without_context, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py:294\n_ ERROR at setup of TestAuthenticationHelper.test_require_authentication_success _\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 330\n      def test_require_authentication_success(self, mock_request_with_context, valid_user_context):\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 294\n      @pytest.fixture\n      def mock_request_with_context(self, valid_user_context):\nE       fixture 'valid_user_context' not found\n>       available fixtures: _class_scoped_runner, _function_scoped_runner, _module_scoped_runner, _package_scoped_runner, _session_scoped_runner, anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, doctest_namespace, event_loop_policy, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, mock_request_with_context, mock_request_without_context, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py:294\n_________ ERROR at setup of TestAuthenticationHelper.test_get_user_id _________\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 340\n      def test_get_user_id(self, mock_request_with_context, valid_user_context):\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 294\n      @pytest.fixture\n      def mock_request_with_context(self, valid_user_context):\nE       fixture 'valid_user_context' not found\n>       available fixtures: _class_scoped_runner, _function_scoped_runner, _module_scoped_runner, _package_scoped_runner, _session_scoped_runner, anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, doctest_namespace, event_loop_policy, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, mock_request_with_context, mock_request_without_context, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py:294\n________ ERROR at setup of TestAuthenticationHelper.test_get_username _________\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 345\n      def test_get_username(self, mock_request_with_context, valid_user_context):\nfile C:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py, line 294\n      @pytest.fixture\n      def mock_request_with_context(self, valid_user_context):\nE       fixture 'valid_user_context' not found\n>       available fixtures: _class_scoped_runner, _function_scoped_runner, _module_scoped_runner, _package_scoped_runner, _session_scoped_runner, anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, doctest_namespace, event_loop_policy, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, mock_request_with_context, mock_request_without_context, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\MBTI_Travel_Assistant\\tests\\test_authentication_integration.py:294\n================================== FAILURES ===================================\n_____________ TestAuthenticationHelper.test_get_user_context_none _____________\ntests\\test_authentication_integration.py:318: in test_get_user_context_none\n    assert user_context is None\nE   AssertionError: assert <Mock name='mock.state.user_context' id='2500901006336'> is None\n____________ TestAuthenticationHelper.test_is_authenticated_false _____________\ntests\\test_authentication_integration.py:328: in test_is_authenticated_false\n    assert is_auth is False\nE   AssertionError: assert <Mock name='mock.state.authenticated' id='2500900431264'> is False\n________ TestAuthenticationHelper.test_require_authentication_failure _________\ntests\\test_authentication_integration.py:337: in test_require_authentication_failure\n    with pytest.raises(Exception):  # HTTPException or similar\nE   Failed: DID NOT RAISE <class 'Exception'>\n=========================== short test summary info ===========================\nFAILED tests/test_authentication_integration.py::TestAuthenticationHelper::test_get_user_context_none\nFAILED tests/test_authentication_integration.py::TestAuthenticationHelper::test_is_authenticated_false\nFAILED tests/test_authentication_integration.py::TestAuthenticationHelper::test_require_authentication_failure\nERROR tests/test_authentication_integration.py::TestAuthenticationHelper::test_get_user_context_success\nERROR tests/test_authentication_integration.py::TestAuthenticationHelper::test_is_authenticated_true\nERROR tests/test_authentication_integration.py::TestAuthenticationHelper::test_require_authentication_success\nERROR tests/test_authentication_integration.py::TestAuthenticationHelper::test_get_user_id\nERROR tests/test_authentication_integration.py::TestAuthenticationHelper::test_get_username\n=================== 3 failed, 19 passed, 5 errors in 1.67s ====================\n",
  "pytest_stderr": "",
  "component_tests": {
    "token_validator_init": true,
    "auth_config_init": true,
    "middleware_factory": true
  },
  "cognito_config_loaded": true,
  "cognito_config": {
    "user_pool_id": "us-east-1_wBAxW7yd4",
    "client_id": "26k0pnja579pdpb1pt6savs27e",
    "region": "us-east-1"
  }
}